#!/bin/sh
currentdir=`pwd`
cd /boot/home/yab_work/BuildFactory
BuildFactory.yab Bookmarker "$currentdir/Bookmarker.yab" application/x-vnd.Bookmarker
mv -T Bookmarker $currentdir/Bookmarker
cd $currentdir
RdefApply bm.rdef Bookmarker
sync
unzip -o Bookmarks
mv  -T Bookmarker "Bookmarks/ Bookmarker"