#!/bin/sh
settings=`finddir B_USER_SETTINGS_DIRECTORY`
DeskBarMenu=`finddir B_USER_DESKBAR_DIRECTORY`
if ! test -e "$DeskBarMenu/Bookmarks"; then
copyattr -n BEOS:ICON  Bookmarks $settings/WebPositive/Bookmarks
ln -sT $settings/WebPositive/Bookmarks $DeskBarMenu/Bookmarks
copyattr -r -d Bookmarks/ $settings/WebPositive
"$DeskBarMenu/Bookmarks/ Bookmarker" &
else
"$DeskBarMenu/Bookmarks/ Bookmarker" &
fi